### ISSUE TITLE
`npm install` step missing from contributing.md

### ISSUE THREAD

**Issue by kdv24** [ahl389/paint-run2#23]
Without `npm install` running, `npm start` errors, so we should explicitly add the instruction.  Probably to the `readme.md` doc as well.

- @ahl389 I hope this is okay to open an issue. I read the contributing guidelines and it didn't mention opening issues, but this seemed like a safe one. I'll go ahead and push the branch with the fix and create a PR too.

I have another one I'd like to open and fix too, but want to get your feedback on the process first.

**Comment by kdv24** [comment]
When I tried to push my branch up, it said I don't have permission. Is there something I need to do? Also, I don't see that I have the ability to assign myself to the issue.  I'm not sure if I'm doing something wrong, or if there are steps that need to be taken on your end (assuming you're all good with me doing this! 😄)

**Comment by ahl389** [comment]
@kdv24 Issues are great! I'll add creating them to the contributing.md.

There's also an error in the package.json file that will cause startup errors. I fixed it at the meetup, but I meant to commit up yesterday but forgot last second. I'll do that now!

**Comment by ahl389** [comment]
Also, I'll add you as a collaborator!

**Comment by ahl389** [comment]
This is fixed now, with a couple other minor updates. Also, you should have gotten the collab invite link!
